const dictionaries = {
  es: {
    projects: "Proyectos", invest: "Invertir", dashboard: "Dashboard", legal: "Ley RD", contact: "Contacto", whatsapp: "WhatsApp",
    heroEyebrow: "Tokenizacion de activos en Solana", heroTitle: "Invierte de forma fraccionada en proyectos dominicanos tokenizados.", heroLead: "Plataforma para originar bienes raices, agricultura, musica, arte, turismo y otros activos; validar inversionistas, estructurar ofertas, emitir tokens controlados y administrar distribuciones.",
    viewProjects: "Ver proyectos", createOrder: "Crear orden", pilotProjects: "Proyectos piloto", targetCapital: "Capital objetivo", reservedCapital: "Capital reservado", pipeline: "Pipeline", readyAssets: "Activos listos para pruebas",
    modulesTitle: "Una plataforma completa para tokenizar activos", modulesLead: "Integramos originacion, cumplimiento, contratos, inversionistas y operaciones en una sola experiencia.", backOffice: "Back office de activos", backOfficeText: "Gestion de cartera, documentos, estados de ofertas, solicitudes de inversionistas y registro de auditoria.", smartContracts: "Motor blockchain", smartContractsText: "Emision controlada de tokens en Solana, reglas de transferencia, whitelist y eventos verificables.", investorPortal: "Portal del inversionista", investorPortalText: "Dashboard con proyectos, tokens, ordenes, distribuciones y documentos relevantes.", landingPages: "Paginas por proyecto", landingPagesText: "Fichas comerciales optimizadas con imagenes, estructura legal, metricas, riesgos y llamados a inversion.", advantagesTitle: "Por que elegir Tokenizas Dominicana", demoTitle: "Agenda una consulta",
    legalTitle: "Marco legal sobre tokens en Republica Dominicana", legalLead: "Republica Dominicana no tiene una ley cripto integral especifica para tokenizacion de activos. El camino prudente es estructurar ofertas que puedan calificar como valores bajo la Ley 249-17 y la supervision de la SIMV, con KYC/AML, documentacion de oferta y proteccion al inversionista. Los criptoactivos no son moneda de curso legal ni tienen respaldo del Banco Central.", legal1: "Un token de proyecto no debe presentarse como titulo de propiedad registrado ni como garantia publica. Normalmente representa un derecho economico, contractual o participacion en un vehiculo legal.", legal2: "Si el token funciona como valor mobiliario, debe revisarse con asesores legales y, cuando aplique, con la Superintendencia del Mercado de Valores.", legal3: "La plataforma debe separar claramente registro legal, contratos, cap table interno y registro blockchain.",
    contactTitle: "Solicita mas informacion", contactLead: "Cuentanos sobre tu proyecto, inmueble o perfil de inversionista. Te contactaremos por email o WhatsApp.", name: "Nombre", company: "Empresa", email: "Email", phone: "WhatsApp", interest: "Interes", message: "Mensaje", consent: "Acepto ser contactado sobre Tokenizas Dominicana.", send: "Enviar solicitud", leadSaved: "Solicitud recibida. Te contactaremos pronto.", confirmSubject: "Recibimos tu solicitud en Tokenizas Dominicana", confirmIntro: "Gracias por contactar a Tokenizas Dominicana.", confirmBody: "Recibimos tu solicitud y nuestro equipo revisara la informacion para responderte pronto por email o WhatsApp.", confirmFooter: "Este mensaje confirma que tu solicitud fue registrada correctamente.",
    loginTitle: "Panel administrativo", loginLead: "Ingresa tus credenciales para administrar proyectos, KYC y auditoria.", privateAccess: "Acceso privado", username: "Usuario", password: "Clave", enter: "Entrar", logout: "Cerrar sesion"
  },
  en: {
    projects: "Projects", invest: "Invest", dashboard: "Dashboard", legal: "DR Law", contact: "Contact", whatsapp: "WhatsApp",
    heroEyebrow: "Asset tokenization on Solana", heroTitle: "Fractional access to tokenized Dominican projects.", heroLead: "A platform to originate real estate, agriculture, music, art, tourism, and other assets; validate investors, structure offerings, issue controlled tokens, and manage distributions.",
    viewProjects: "View projects", createOrder: "Create order", pilotProjects: "Pilot projects", targetCapital: "Target capital", reservedCapital: "Reserved capital", pipeline: "Pipeline", readyAssets: "Assets ready for testing",
    modulesTitle: "A complete platform for asset tokenization", modulesLead: "Origination, compliance, contracts, investors, and operations in one experience.", backOffice: "Asset back office", backOfficeText: "Portfolio management, documents, offering status, investor requests, and audit records.", smartContracts: "Blockchain engine", smartContractsText: "Controlled Solana token issuance, transfer rules, whitelist, and verifiable events.", investorPortal: "Investor portal", investorPortalText: "Dashboard with projects, tokens, orders, distributions, and documents.", landingPages: "Project pages", landingPagesText: "Commercial pages with images, legal structure, metrics, risks, and investment calls to action.", advantagesTitle: "Why choose Tokenizas Dominicana", demoTitle: "Book a consultation",
    legalTitle: "Token law in the Dominican Republic", legalLead: "The Dominican Republic does not yet have a comprehensive crypto statute specifically for asset tokenization. The prudent route is to structure offerings that may qualify as securities under Law 249-17 and SIMV supervision, with KYC/AML, offering documents, and investor protection. Cryptoassets are not legal tender and are not backed by the Central Bank.", legal1: "A project token should not be presented as a registered property title or public guarantee. It usually represents an economic, contractual, or vehicle-level right.", legal2: "If the token behaves as a security, it should be reviewed by counsel and, where applicable, the securities regulator.", legal3: "The platform must clearly separate the legal registry, contracts, internal cap table, and blockchain record.",
    contactTitle: "Request more information", contactLead: "Tell us about your project, property, or investor profile. We will contact you by email or WhatsApp.", name: "Name", company: "Company", email: "Email", phone: "WhatsApp", interest: "Interest", message: "Message", consent: "I agree to be contacted about Tokenizas Dominicana.", send: "Send request", leadSaved: "Request received. We will contact you soon.", confirmSubject: "We received your request at Tokenizas Dominicana", confirmIntro: "Thank you for contacting Tokenizas Dominicana.", confirmBody: "We received your request and our team will review the information to reply soon by email or WhatsApp.", confirmFooter: "This message confirms that your request was registered successfully.",
    loginTitle: "Admin panel", loginLead: "Enter your credentials to manage projects, KYC, and audit records.", privateAccess: "Private access", username: "Username", password: "Password", enter: "Sign in", logout: "Log out"
  },
  de: {
    projects: "Projekte", invest: "Investieren", dashboard: "Dashboard", legal: "Recht RD", contact: "Kontakt", whatsapp: "WhatsApp",
    heroEyebrow: "Asset-Tokenisierung auf Solana", heroTitle: "Fraktionierter Zugang zu tokenisierten Projekten in der Dominikanischen Republik.", heroLead: "Plattform fuer Immobilien, Landwirtschaft, Musik, Kunst, Tourismus und weitere Assets; mit Investorenpruefung, Angebotsstrukturierung, kontrollierter Token-Ausgabe und Ausschuettungen.",
    viewProjects: "Projekte ansehen", createOrder: "Order erstellen", pilotProjects: "Pilotprojekte", targetCapital: "Zielkapital", reservedCapital: "Reserviertes Kapital", pipeline: "Pipeline", readyAssets: "Assets fuer Tests bereit",
    modulesTitle: "Eine komplette Plattform fuer Asset-Tokenisierung", modulesLead: "Originierung, Compliance, Vertraege, Investoren und Betrieb in einer Erfahrung.", backOffice: "Asset Back Office", backOfficeText: "Portfolioverwaltung, Dokumente, Angebotsstatus, Investorenanfragen und Auditprotokolle.", smartContracts: "Blockchain Engine", smartContractsText: "Kontrollierte Solana-Token-Ausgabe, Transferregeln, Whitelist und pruefbare Events.", investorPortal: "Investorenportal", investorPortalText: "Dashboard mit Projekten, Tokens, Orders, Ausschuettungen und Dokumenten.", landingPages: "Projektseiten", landingPagesText: "Kommerzielle Seiten mit Bildern, Rechtsstruktur, Kennzahlen, Risiken und Investment-Aufrufen.", advantagesTitle: "Warum Tokenizas Dominicana", demoTitle: "Beratung buchen",
    legalTitle: "Token-Rechtslage in der Dominikanischen Republik", legalLead: "Die Dominikanische Republik hat noch kein umfassendes Kryptogesetz speziell fuer Asset-Tokenisierung. Der vorsichtige Weg ist eine Strukturierung als moegliches Wertpapier unter Gesetz 249-17 und SIMV-Aufsicht, mit KYC/AML, Offenlegungsunterlagen und Investorenschutz.", legal1: "Ein Projekt-Token sollte nicht als registrierter Eigentumstitel oder oeffentliche Garantie dargestellt werden. Meist repraesentiert er ein wirtschaftliches, vertragliches oder vehikelbezogenes Recht.", legal2: "Wenn der Token wie ein Wertpapier wirkt, sollte er rechtlich und gegebenenfalls mit der Wertpapieraufsicht geprueft werden.", legal3: "Die Plattform muss Grundbuch, Vertraege, interne Beteiligungstabelle und Blockchain-Eintrag klar trennen.",
    contactTitle: "Weitere Informationen anfordern", contactLead: "Erzaehle uns von deinem Projekt, deiner Immobilie oder deinem Anlegerprofil. Wir melden uns per E-Mail oder WhatsApp.", name: "Name", company: "Unternehmen", email: "E-Mail", phone: "WhatsApp", interest: "Interesse", message: "Nachricht", consent: "Ich stimme zu, zu Tokenizas Dominicana kontaktiert zu werden.", send: "Anfrage senden", leadSaved: "Anfrage erhalten. Wir melden uns bald.", confirmSubject: "Wir haben deine Anfrage bei Tokenizas Dominicana erhalten", confirmIntro: "Vielen Dank fuer deine Kontaktaufnahme mit Tokenizas Dominicana.", confirmBody: "Wir haben deine Anfrage erhalten und unser Team prueft die Informationen, um bald per E-Mail oder WhatsApp zu antworten.", confirmFooter: "Diese Nachricht bestaetigt, dass deine Anfrage erfolgreich registriert wurde.",
    loginTitle: "Adminbereich", loginLead: "Melde dich an, um Projekte, KYC und Auditdaten zu verwalten.", privateAccess: "Privater Zugang", username: "Benutzer", password: "Passwort", enter: "Einloggen", logout: "Abmelden"
  },
  fr: {
    projects: "Projets", invest: "Investir", dashboard: "Tableau", legal: "Loi RD", contact: "Contact", whatsapp: "WhatsApp",
    heroEyebrow: "Tokenisation d'actifs sur Solana", heroTitle: "Acces fractionne aux projets dominicains tokenises.", heroLead: "Plateforme pour sourcer immobilier, agriculture, musique, art, tourisme et autres actifs; verifier les investisseurs, structurer les offres, emettre des tokens controles et gerer les distributions.",
    viewProjects: "Voir les projets", createOrder: "Creer un ordre", pilotProjects: "Projets pilotes", targetCapital: "Capital cible", reservedCapital: "Capital reserve", pipeline: "Pipeline", readyAssets: "Actifs prets pour les tests",
    modulesTitle: "Une plateforme complete pour la tokenisation d'actifs", modulesLead: "Origination, conformite, contrats, investisseurs et operations dans une seule experience.", backOffice: "Back office actifs", backOfficeText: "Gestion de portefeuille, documents, statut des offres, demandes investisseurs et audit.", smartContracts: "Moteur blockchain", smartContractsText: "Emission controlee de tokens Solana, regles de transfert, whitelist et evenements verifiables.", investorPortal: "Portail investisseur", investorPortalText: "Tableau avec projets, tokens, ordres, distributions et documents.", landingPages: "Pages projet", landingPagesText: "Pages commerciales avec images, structure legale, indicateurs, risques et appels a investir.", advantagesTitle: "Pourquoi choisir Tokenizas Dominicana", demoTitle: "Planifier une consultation",
    legalTitle: "Cadre juridique des tokens en Republique dominicaine", legalLead: "La Republique dominicaine ne dispose pas encore d'une loi crypto complete specifique a la tokenisation d'actifs. La voie prudente consiste a structurer les offres pouvant etre qualifiees de valeurs mobilieres sous la Loi 249-17 et la supervision de la SIMV, avec KYC/AML, documents d'information et protection des investisseurs.", legal1: "Un token de projet ne doit pas etre presente comme un titre de propriete enregistre ni comme une garantie publique. Il represente generalement un droit economique, contractuel ou lie a un vehicule juridique.", legal2: "Si le token fonctionne comme une valeur mobiliere, il doit etre examine par des conseillers juridiques et, le cas echeant, par le regulateur des valeurs mobilieres.", legal3: "La plateforme doit separer clairement le registre legal, les contrats, le cap table interne et l'enregistrement blockchain.",
    contactTitle: "Demander plus d'informations", contactLead: "Parlez-nous de votre projet, bien immobilier ou profil investisseur. Nous vous contacterons par email ou WhatsApp.", name: "Nom", company: "Entreprise", email: "Email", phone: "WhatsApp", interest: "Interet", message: "Message", consent: "J'accepte d'etre contacte au sujet de Tokenizas Dominicana.", send: "Envoyer", leadSaved: "Demande recue. Nous vous contacterons bientot.", confirmSubject: "Nous avons recu votre demande chez Tokenizas Dominicana", confirmIntro: "Merci d'avoir contacte Tokenizas Dominicana.", confirmBody: "Nous avons recu votre demande et notre equipe examinera les informations pour vous repondre bientot par email ou WhatsApp.", confirmFooter: "Ce message confirme que votre demande a bien ete enregistree.",
    loginTitle: "Panneau admin", loginLead: "Connectez-vous pour gerer les projets, KYC et journaux d'audit.", privateAccess: "Acces prive", username: "Utilisateur", password: "Mot de passe", enter: "Connexion", logout: "Deconnexion"
  }
};

const shared = {
  es: {
    tokenize: "Tokenizar",
    back: "Volver",
    save: "Guardar",
    download: "Descargar",
    file: "Archivo",
    status: "Estado",
    date: "Fecha",
    country: "Pais",
    location: "Ubicacion",
    wallet: "Wallet",
    currentPassword: "Clave actual",
    newPassword: "Nueva clave",
    confirmPassword: "Confirmar nueva clave",
    categoryLabels: { "real-estate": "Bienes raices", agriculture: "Agricultura", art: "Arte", music: "Musica", tourism: "Turismo", business: "Negocios", energy: "Energia" },
    statusLabels: { open: "Abierto", due_diligence: "Due diligence", funded: "Financiado", tokens_issued: "Tokens emitidos", compliance_review: "Revision compliance", pending_payment: "Pago pendiente", approved: "Aprobado", rejected: "Rechazado", submitted: "Enviado", review: "En revision", needs_more_info: "Falta informacion", not_started: "No iniciado", new: "Nuevo", contacted: "Contactado", qualified: "Calificado", proposal: "Propuesta", closed: "Cerrado", archived: "Archivado" },
    investor: {
      portal: "Portal inversionista", register: "Crear cuenta", login: "Entrar", registerLead: "Crea tu acceso para invertir, completar KYC y ver tus ordenes.", loginLead: "Accede a tus ordenes, KYC, wallet y documentos.", fullName: "Nombre completo", residenceCountry: "Pais de residencia", solanaWallet: "Wallet Solana", optionalNow: "Opcional por ahora", alreadyAccount: "Ya tienes cuenta?", noAccount: "No tienes cuenta?", completeFields: "Completa los campos y usa una clave de 10 caracteres o mas.", emailExists: "Ese email ya esta registrado.", badLogin: "Email o clave incorrectos.", createOrder: "Crear orden", completeKyc: "Completar KYC", exit: "Salir", reserved: "Reservado", kycDocuments: "Documentos KYC", myOrders: "Mis ordenes", noOrders: "Todavia no tienes ordenes.", missingDocs: "Faltan documentos para completar tu expediente.", kycSubmitted: "Expediente KYC enviado para revision.", noUploadedDocs: "Sin documentos subidos.", kycTitle: "Completar expediente", kycLead: "Sube documentos claros en PDF, JPG, PNG o WebP. Maximo 8 MB por archivo.", uploadDocument: "Subir documento", documentType: "Tipo de documento", sentDocuments: "Documentos enviados", noDocumentsYet: "Sin documentos todavia.", invalidDocType: "Tipo de documento invalido.", selectDocument: "Selecciona un documento.", allowedFiles: "Solo se permiten PDF, JPG, PNG o WebP.", documentTypes: { identity: "Cedula o pasaporte", selfie: "Selfie / prueba de vida", address: "Comprobante de direccion", funds: "Origen de fondos", investor_profile: "Perfil de inversionista" }
    },
    issuer: {
      nav: "Tokenizar", applyTitle: "Aplicar para tokenizar un proyecto", eyebrow: "Dueños de proyecto", applyLead: "Completa la informacion legal, presupuesto, permisos y documentos para una revision inicial.", ownerData: "Datos del dueño", ownerName: "Nombre del responsable", companyName: "Empresa / vehiculo legal", legalOwner: "Titular legal del activo", projectBudget: "Proyecto y presupuesto", projectName: "Nombre del proyecto", targetRaise: "Monto a recaudar USD", totalBudget: "Presupuesto total USD", budgetBreakdown: "Detalle del presupuesto", budgetPlaceholder: "Ej: terreno, permisos, construccion, equipos, marketing, operacion, reserva legal.", legalStructure: "Estructura legal propuesta", legalPlaceholder: "Ej: fideicomiso, SRL/SPV, contrato de participacion economica, deuda privada, revenue share.", permitsSummary: "Permisos y autorizaciones disponibles o pendientes", description: "Descripcion del proyecto", initialDocuments: "Documentos iniciales", submit: "Enviar solicitud", permitsGuideTitle: "Guia de permisos RD", legalNotice: "Esta guia no sustituye una opinion legal. Cada proyecto debe ser revisado por abogados y asesores regulados en Republica Dominicana.", completeRequired: "Completa todos los campos requeridos.", successTitle: "Tu proyecto fue enviado para revision", successEyebrow: "Solicitud recibida", successLead: "El equipo revisara presupuesto, permisos, estructura legal y documentos antes de publicar o tokenizar.", requestNumber: "Numero de solicitud", contactTeam: "Contactar equipo", documentTypes: { owner_id: "Cedula/pasaporte del dueno o representante", company_registry: "Registro Mercantil / RNC / estatutos", property_title: "Titulo, contrato, derecho economico o prueba de propiedad", tax_clearance: "Certificaciones fiscales y no objeciones aplicables", permit_authority: "Permisos, licencias o autorizaciones sectoriales", budget: "Presupuesto detallado y cotizaciones", financial_model: "Modelo financiero y uso de fondos", legal_opinion: "Opinion legal / estructura de oferta" },
      permitsGuide: ["Bienes raices: titulo o contrato, certificacion registral, deslinde si aplica, tasacion, permisos municipales, uso de suelo, licencia de construccion si hay desarrollo, autorizaciones ambientales cuando correspondan.", "Turismo: documentacion de propiedad o arrendamiento, permisos municipales, licencias turisticas aplicables, autorizaciones de operacion, permisos ambientales y sanitarios segun el tipo de proyecto.", "Agricultura: prueba de tenencia o arrendamiento, permisos de uso de agua si aplica, registros sanitarios/agricolas, permisos ambientales cuando haya impacto, presupuesto de siembra, mantenimiento y cosecha.", "Arte y musica: prueba de titularidad o derechos de explotacion, contratos de artista/productor, presupuesto de produccion, licencias, plan de ingresos y autorizaciones de imagen/marca.", "Energia: concesiones, permisos ambientales, interconexion, estudios tecnicos, contratos de compra de energia y autorizaciones regulatorias aplicables."]
    }
    , projectPages: { tokenizable: "Proyectos tokenizables", primaryMarket: "Marketplace primario", category: "Categoria", all: "Todos", empty: "Todavia no hay proyectos publicados aqui.", marketplaceTitle: "Marketplace tokenizado", marketplaceEyebrow: "Tokens configurados", marketplaceLead: "Proyectos que ya tienen mint configurado y estan listos para ordenes, reservas o emision operativa.", offerStructure: "Estructura de la oferta", reservedOf: "reservados de", investAmount: "Monto a invertir", paymentMethod: "Metodo de pago", testOrder: "Crear orden de prueba", keyData: "Datos clave", target: "Meta", minimum: "Minimo", expectedYield: "Rendimiento esperado", open: "Abrir", risk: "Riesgo", months: "meses", documents: "Documentos", solanaEvents: "Eventos Solana simulados", notFound: "Proyecto no encontrado", categoryTitles: { "real-estate": "Proyectos inmobiliarios", agriculture: "Proyectos de agricultura", art: "Proyectos de arte", music: "Proyectos de musica", tourism: "Proyectos de turismo", business: "Proyectos de negocios", energy: "Proyectos de energia" } }
    , legalRulesTitle: "Reglas operativas para tokenizar en RD", legalSourcesTitle: "Fuentes regulatorias de referencia", legalSourcesText: "Para produccion real se debe validar con abogados dominicanos, la Superintendencia del Mercado de Valores, la Direccion General de Impuestos Internos, la Unidad de Analisis Financiero y politicas del Banco Central sobre activos virtuales.", legalRules: [
      ["Sin ley cripto especifica", "Republica Dominicana no tiene una ley integral especifica para blockchain o tokenizacion. Cada oferta debe analizarse bajo leyes existentes de valores, sociedades, impuestos, lavado de activos, datos personales y propiedad."],
      ["No es moneda legal", "Los criptoactivos no son moneda de curso legal ni cuentan con respaldo del Banco Central. La plataforma debe evitar presentarlos como dinero oficial o garantia estatal."],
      ["SIMV y Ley 249-17", "Si el token promete rendimiento, participacion economica, deuda, revenue share o expectativa de ganancia por gestion de terceros, puede ser tratado como valor y requerir analisis bajo la Ley del Mercado de Valores y supervision de la SIMV."],
      ["AML/KYC obligatorio", "Bajo la Ley 155-17 y criterios de la UAF, el flujo debe identificar inversionistas y promotores, revisar origen de fondos, beneficiario final, PEP, sanciones y monitoreo de operaciones."],
      ["Impuestos y DGII", "Ingresos, distribuciones, ganancias, ITBIS si aplica, retenciones y reportes fiscales deben revisarse con contadores locales antes de publicar una oferta."],
      ["Datos personales", "Documentos KYC, cedulas, pasaportes y estados financieros deben guardarse con acceso restringido, finalidad clara, consentimiento y controles de seguridad."]
    ]
  },
  en: {
    tokenize: "Tokenize", back: "Back", save: "Save", download: "Download", file: "File", status: "Status", date: "Date", country: "Country", location: "Location", wallet: "Wallet", currentPassword: "Current password", newPassword: "New password", confirmPassword: "Confirm new password",
    categoryLabels: { "real-estate": "Real estate", agriculture: "Agriculture", art: "Art", music: "Music", tourism: "Tourism", business: "Business", energy: "Energy" },
    statusLabels: { open: "Open", due_diligence: "Due diligence", funded: "Funded", tokens_issued: "Tokens issued", compliance_review: "Compliance review", pending_payment: "Payment pending", approved: "Approved", rejected: "Rejected", submitted: "Submitted", review: "In review", needs_more_info: "More information needed", not_started: "Not started", new: "New", contacted: "Contacted", qualified: "Qualified", proposal: "Proposal", closed: "Closed", archived: "Archived" },
    investor: { portal: "Investor portal", register: "Create account", login: "Sign in", registerLead: "Create access to invest, complete KYC, and view your orders.", loginLead: "Access your orders, KYC, wallet, and documents.", fullName: "Full name", residenceCountry: "Country of residence", solanaWallet: "Solana wallet", optionalNow: "Optional for now", alreadyAccount: "Already have an account?", noAccount: "No account yet?", completeFields: "Complete all fields and use a password of 10 characters or more.", emailExists: "That email is already registered.", badLogin: "Incorrect email or password.", createOrder: "Create order", completeKyc: "Complete KYC", exit: "Log out", reserved: "Reserved", kycDocuments: "KYC documents", myOrders: "My orders", noOrders: "You do not have orders yet.", missingDocs: "Documents are missing to complete your file.", kycSubmitted: "KYC file submitted for review.", noUploadedDocs: "No uploaded documents.", kycTitle: "Complete your file", kycLead: "Upload clear documents in PDF, JPG, PNG, or WebP. Maximum 8 MB per file.", uploadDocument: "Upload document", documentType: "Document type", sentDocuments: "Submitted documents", noDocumentsYet: "No documents yet.", invalidDocType: "Invalid document type.", selectDocument: "Select a document.", allowedFiles: "Only PDF, JPG, PNG, or WebP files are allowed.", documentTypes: { identity: "ID card or passport", selfie: "Selfie / liveness proof", address: "Proof of address", funds: "Source of funds", investor_profile: "Investor profile" } },
    issuer: { nav: "Tokenize", applyTitle: "Apply to tokenize a project", eyebrow: "Project owners", applyLead: "Complete legal information, budget, permits, and documents for an initial review.", ownerData: "Owner information", ownerName: "Responsible person", companyName: "Company / legal vehicle", legalOwner: "Legal owner of the asset", projectBudget: "Project and budget", projectName: "Project name", targetRaise: "Target raise USD", totalBudget: "Total budget USD", budgetBreakdown: "Budget breakdown", budgetPlaceholder: "Example: land, permits, construction, equipment, marketing, operations, legal reserve.", legalStructure: "Proposed legal structure", legalPlaceholder: "Example: trust, LLC/SPV, economic participation agreement, private debt, revenue share.", permitsSummary: "Available or pending permits and authorizations", description: "Project description", initialDocuments: "Initial documents", submit: "Submit application", permitsGuideTitle: "DR permits guide", legalNotice: "This guide does not replace a legal opinion. Each project must be reviewed by lawyers and regulated advisers in the Dominican Republic.", completeRequired: "Complete all required fields.", successTitle: "Your project was submitted for review", successEyebrow: "Application received", successLead: "The team will review the budget, permits, legal structure, and documents before publication or tokenization.", requestNumber: "Application number", contactTeam: "Contact team", documentTypes: { owner_id: "Owner/representative ID or passport", company_registry: "Commercial registry / tax ID / bylaws", property_title: "Title, contract, economic right, or proof of ownership", tax_clearance: "Tax certificates and applicable no-objection letters", permit_authority: "Sector permits, licenses, or authorizations", budget: "Detailed budget and quotes", financial_model: "Financial model and use of funds", legal_opinion: "Legal opinion / offering structure" }, permitsGuide: ["Real estate: title or contract, registry certificate, survey if applicable, appraisal, municipal permits, zoning/use of land, construction license if applicable, environmental authorizations when required.", "Tourism: ownership or lease documents, municipal permits, applicable tourism licenses, operating authorizations, environmental and health permits depending on the project.", "Agriculture: proof of tenure or lease, water-use permits if applicable, agricultural/health registrations, environmental permits when there is impact, planting, maintenance, and harvest budget.", "Art and music: proof of ownership or exploitation rights, artist/producer contracts, production budget, licenses, revenue plan, and image/brand authorizations.", "Energy: concessions, environmental permits, interconnection, technical studies, power purchase contracts, and applicable regulatory authorizations."] }
    , projectPages: { tokenizable: "Tokenizable projects", primaryMarket: "Primary marketplace", category: "Category", all: "All", empty: "No projects have been published here yet.", marketplaceTitle: "Tokenized marketplace", marketplaceEyebrow: "Configured tokens", marketplaceLead: "Projects that already have a configured mint and are ready for orders, reservations, or operational issuance.", offerStructure: "Offering structure", reservedOf: "reserved of", investAmount: "Investment amount", paymentMethod: "Payment method", testOrder: "Create test order", keyData: "Key data", target: "Target", minimum: "Minimum", expectedYield: "Expected yield", open: "Open", risk: "Risk", months: "months", documents: "Documents", solanaEvents: "Simulated Solana events", notFound: "Project not found", categoryTitles: { "real-estate": "Real estate projects", agriculture: "Agriculture projects", art: "Art projects", music: "Music projects", tourism: "Tourism projects", business: "Business projects", energy: "Energy projects" } }
    , legalRulesTitle: "Operating rules for tokenization in the DR", legalSourcesTitle: "Regulatory reference sources", legalSourcesText: "For production use, validate with Dominican counsel, the Securities Market Superintendence, the tax authority, the Financial Analysis Unit, and Central Bank policies on virtual assets.", legalRules: [
      ["No specific crypto statute", "The Dominican Republic does not have a comprehensive statute specifically for blockchain or tokenization. Each offering must be reviewed under existing securities, corporate, tax, AML, data protection, and property rules."],
      ["Not legal tender", "Cryptoassets are not legal tender and are not backed by the Central Bank. The platform must not present them as official money or state-guaranteed instruments."],
      ["SIMV and Law 249-17", "If a token promises yield, economic participation, debt, revenue share, or profit expectation from third-party management, it may be treated as a security and require analysis under securities law and SIMV supervision."],
      ["AML/KYC required", "Under Law 155-17 and UAF criteria, the flow must identify investors and promoters, review source of funds, beneficial owners, PEP status, sanctions, and transaction monitoring."],
      ["Taxes and DGII", "Income, distributions, gains, VAT where applicable, withholding, and tax reports must be reviewed with local accountants before publishing an offering."],
      ["Personal data", "KYC documents, IDs, passports, and financial statements must be stored with restricted access, clear purpose, consent, and security controls."]
    ]
  },
  de: {},
  fr: {}
};

shared.de = JSON.parse(JSON.stringify(shared.en));
Object.assign(shared.de, {
  tokenize: "Tokenisieren", back: "Zurueck", save: "Speichern", download: "Herunterladen", file: "Datei", status: "Status", date: "Datum", country: "Land", location: "Standort", currentPassword: "Aktuelles Passwort", newPassword: "Neues Passwort", confirmPassword: "Neues Passwort bestaetigen",
  categoryLabels: { "real-estate": "Immobilien", agriculture: "Landwirtschaft", art: "Kunst", music: "Musik", tourism: "Tourismus", business: "Geschaeft", energy: "Energie" },
  statusLabels: { open: "Offen", due_diligence: "Due Diligence", funded: "Finanziert", tokens_issued: "Tokens ausgegeben", compliance_review: "Compliance-Pruefung", pending_payment: "Zahlung ausstehend", approved: "Genehmigt", rejected: "Abgelehnt", submitted: "Eingereicht", review: "In Pruefung", needs_more_info: "Weitere Informationen erforderlich", not_started: "Nicht begonnen", new: "Neu", contacted: "Kontaktiert", qualified: "Qualifiziert", proposal: "Angebot", closed: "Geschlossen", archived: "Archiviert" }
});
Object.assign(shared.de.investor, { portal: "Investorenportal", register: "Konto erstellen", login: "Einloggen", registerLead: "Erstelle Zugang, um zu investieren, KYC abzuschliessen und deine Orders zu sehen.", loginLead: "Greife auf Orders, KYC, Wallet und Dokumente zu.", fullName: "Vollstaendiger Name", residenceCountry: "Wohnsitzland", solanaWallet: "Solana-Wallet", optionalNow: "Derzeit optional", alreadyAccount: "Schon ein Konto?", noAccount: "Noch kein Konto?", completeFields: "Fuellen Sie alle Felder aus und nutzen Sie ein Passwort mit mindestens 10 Zeichen.", emailExists: "Diese E-Mail ist bereits registriert.", badLogin: "E-Mail oder Passwort ist falsch.", createOrder: "Order erstellen", completeKyc: "KYC abschliessen", exit: "Abmelden", reserved: "Reserviert", kycDocuments: "KYC-Dokumente", myOrders: "Meine Orders", noOrders: "Du hast noch keine Orders.", missingDocs: "Es fehlen Dokumente fuer deine Akte.", kycSubmitted: "KYC-Akte zur Pruefung eingereicht.", noUploadedDocs: "Keine Dokumente hochgeladen.", kycTitle: "Akte vervollstaendigen", kycLead: "Lade klare Dokumente als PDF, JPG, PNG oder WebP hoch. Maximal 8 MB pro Datei.", uploadDocument: "Dokument hochladen", documentType: "Dokumenttyp", sentDocuments: "Eingereichte Dokumente", noDocumentsYet: "Noch keine Dokumente.", invalidDocType: "Ungueltiger Dokumenttyp.", selectDocument: "Waehle ein Dokument aus.", allowedFiles: "Nur PDF, JPG, PNG oder WebP sind erlaubt.", documentTypes: { identity: "Ausweis oder Reisepass", selfie: "Selfie / Lebendigkeitsnachweis", address: "Adressnachweis", funds: "Herkunft der Mittel", investor_profile: "Investorenprofil" } });
Object.assign(shared.de.issuer, { nav: "Tokenisieren", applyTitle: "Projekt zur Tokenisierung einreichen", eyebrow: "Projektinhaber", applyLead: "Reiche Rechtsdaten, Budget, Genehmigungen und Dokumente fuer eine Erstpruefung ein.", ownerData: "Inhaberdaten", ownerName: "Verantwortliche Person", companyName: "Unternehmen / Rechtsvehikel", legalOwner: "Rechtlicher Eigentuemer des Assets", projectBudget: "Projekt und Budget", projectName: "Projektname", targetRaise: "Zielbetrag USD", totalBudget: "Gesamtbudget USD", budgetBreakdown: "Budgetaufschluesselung", legalStructure: "Vorgeschlagene Rechtsstruktur", permitsSummary: "Vorhandene oder ausstehende Genehmigungen", description: "Projektbeschreibung", initialDocuments: "Erste Dokumente", submit: "Antrag senden", permitsGuideTitle: "Genehmigungsleitfaden RD", legalNotice: "Dieser Leitfaden ersetzt keine Rechtsberatung. Jedes Projekt muss von Anwaelten und regulierten Beratern in der Dominikanischen Republik geprueft werden.", completeRequired: "Fuellen Sie alle Pflichtfelder aus.", successTitle: "Dein Projekt wurde zur Pruefung eingereicht", successEyebrow: "Antrag erhalten", successLead: "Das Team prueft Budget, Genehmigungen, Rechtsstruktur und Dokumente vor Veroeffentlichung oder Tokenisierung.", requestNumber: "Antragsnummer", contactTeam: "Team kontaktieren" });
Object.assign(shared.de.projectPages, { tokenizable: "Tokenisierbare Projekte", primaryMarket: "Primaermarkt", category: "Kategorie", all: "Alle", empty: "Hier wurden noch keine Projekte veroeffentlicht.", marketplaceTitle: "Tokenisierter Marktplatz", marketplaceEyebrow: "Konfigurierte Tokens", marketplaceLead: "Projekte mit bereits konfiguriertem Mint, bereit fuer Orders, Reservierungen oder operative Ausgabe.", offerStructure: "Angebotsstruktur", reservedOf: "reserviert von", investAmount: "Investitionsbetrag", paymentMethod: "Zahlungsmethode", testOrder: "Testorder erstellen", keyData: "Kerndaten", target: "Ziel", minimum: "Minimum", expectedYield: "Erwartete Rendite", open: "Oeffnen", risk: "Risiko", months: "Monate", documents: "Dokumente", solanaEvents: "Simulierte Solana-Events", notFound: "Projekt nicht gefunden", categoryTitles: { "real-estate": "Immobilienprojekte", agriculture: "Landwirtschaftsprojekte", art: "Kunstprojekte", music: "Musikprojekte", tourism: "Tourismusprojekte", business: "Geschaeftsprojekte", energy: "Energieprojekte" } });
Object.assign(shared.de, { legalRulesTitle: "Operative Regeln fuer Tokenisierung in der DR", legalSourcesTitle: "Regulatorische Referenzen", legalSourcesText: "Fuer produktive Nutzung mit dominikanischen Anwaelten, Wertpapieraufsicht, Steuerbehoerde, Finanzanalyse-Einheit und Zentralbankpositionen zu virtuellen Assets pruefen.", legalRules: [["Kein spezielles Kryptogesetz", "Die Dominikanische Republik hat kein umfassendes Gesetz speziell fuer Blockchain oder Tokenisierung. Jede Offerte muss unter bestehenden Regeln zu Wertpapieren, Gesellschaften, Steuern, AML, Daten und Eigentum geprueft werden."], ["Kein gesetzliches Zahlungsmittel", "Kryptoassets sind kein gesetzliches Zahlungsmittel und nicht von der Zentralbank gedeckt. Die Plattform darf sie nicht als offizielles Geld oder staatlich garantierte Instrumente darstellen."], ["SIMV und Gesetz 249-17", "Wenn ein Token Rendite, wirtschaftliche Beteiligung, Schuld, Revenue Share oder Gewinnerwartung aus Drittmanagement verspricht, kann er als Wertpapier behandelt werden."], ["AML/KYC erforderlich", "Nach Gesetz 155-17 und UAF-Kriterien muessen Investoren und Promotoren identifiziert, Mittelherkunft, wirtschaftlich Berechtigte, PEP, Sanktionen und Transaktionen geprueft werden."], ["Steuern und DGII", "Einkommen, Ausschuettungen, Gewinne, ITBIS falls anwendbar, Quellensteuern und Steuerberichte muessen lokal geprueft werden."], ["Personenbezogene Daten", "KYC-Dokumente, Ausweise, Paesse und Finanzunterlagen muessen mit eingeschraenktem Zugriff, Zweckbindung, Zustimmung und Sicherheitskontrollen gespeichert werden."]] });

shared.fr = JSON.parse(JSON.stringify(shared.en));
Object.assign(shared.fr, {
  tokenize: "Tokeniser", back: "Retour", save: "Enregistrer", download: "Telecharger", file: "Fichier", status: "Statut", date: "Date", country: "Pays", location: "Localisation", currentPassword: "Mot de passe actuel", newPassword: "Nouveau mot de passe", confirmPassword: "Confirmer le nouveau mot de passe",
  categoryLabels: { "real-estate": "Immobilier", agriculture: "Agriculture", art: "Art", music: "Musique", tourism: "Tourisme", business: "Affaires", energy: "Energie" },
  statusLabels: { open: "Ouvert", due_diligence: "Due diligence", funded: "Finance", tokens_issued: "Tokens emis", compliance_review: "Verification compliance", pending_payment: "Paiement en attente", approved: "Approuve", rejected: "Rejete", submitted: "Envoye", review: "En verification", needs_more_info: "Informations requises", not_started: "Non commence", new: "Nouveau", contacted: "Contacte", qualified: "Qualifie", proposal: "Proposition", closed: "Ferme", archived: "Archive" }
});
Object.assign(shared.fr.investor, { portal: "Portail investisseur", register: "Creer un compte", login: "Connexion", registerLead: "Creez votre acces pour investir, completer le KYC et voir vos ordres.", loginLead: "Accedez a vos ordres, KYC, wallet et documents.", fullName: "Nom complet", residenceCountry: "Pays de residence", solanaWallet: "Wallet Solana", optionalNow: "Optionnel pour l'instant", alreadyAccount: "Vous avez deja un compte?", noAccount: "Pas encore de compte?", completeFields: "Completez tous les champs et utilisez un mot de passe d'au moins 10 caracteres.", emailExists: "Cet email est deja enregistre.", badLogin: "Email ou mot de passe incorrect.", createOrder: "Creer un ordre", completeKyc: "Completer le KYC", exit: "Deconnexion", reserved: "Reserve", kycDocuments: "Documents KYC", myOrders: "Mes ordres", noOrders: "Vous n'avez pas encore d'ordres.", missingDocs: "Des documents manquent pour completer votre dossier.", kycSubmitted: "Dossier KYC envoye pour verification.", noUploadedDocs: "Aucun document envoye.", kycTitle: "Completer le dossier", kycLead: "Telechargez des documents lisibles en PDF, JPG, PNG ou WebP. Maximum 8 MB par fichier.", uploadDocument: "Telecharger un document", documentType: "Type de document", sentDocuments: "Documents envoyes", noDocumentsYet: "Aucun document pour le moment.", invalidDocType: "Type de document invalide.", selectDocument: "Selectionnez un document.", allowedFiles: "Seuls les fichiers PDF, JPG, PNG ou WebP sont autorises.", documentTypes: { identity: "Carte d'identite ou passeport", selfie: "Selfie / preuve de vie", address: "Justificatif de domicile", funds: "Origine des fonds", investor_profile: "Profil investisseur" } });
Object.assign(shared.fr.issuer, { nav: "Tokeniser", applyTitle: "Demander la tokenisation d'un projet", eyebrow: "Porteurs de projet", applyLead: "Completez les informations juridiques, le budget, les permis et les documents pour une premiere verification.", ownerData: "Informations du porteur", ownerName: "Responsable", companyName: "Entreprise / vehicule juridique", legalOwner: "Titulaire legal de l'actif", projectBudget: "Projet et budget", projectName: "Nom du projet", targetRaise: "Montant a lever USD", totalBudget: "Budget total USD", budgetBreakdown: "Detail du budget", legalStructure: "Structure juridique proposee", permitsSummary: "Permis et autorisations disponibles ou en attente", description: "Description du projet", initialDocuments: "Documents initiaux", submit: "Envoyer la demande", permitsGuideTitle: "Guide des permis RD", legalNotice: "Ce guide ne remplace pas un avis juridique. Chaque projet doit etre examine par des avocats et conseillers regules en Republique dominicaine.", completeRequired: "Completez tous les champs obligatoires.", successTitle: "Votre projet a ete envoye pour verification", successEyebrow: "Demande recue", successLead: "L'equipe examinera le budget, les permis, la structure juridique et les documents avant publication ou tokenisation.", requestNumber: "Numero de demande", contactTeam: "Contacter l'equipe" });
Object.assign(shared.fr.projectPages, { tokenizable: "Projets tokenisables", primaryMarket: "Marketplace primaire", category: "Categorie", all: "Tous", empty: "Aucun projet n'a encore ete publie ici.", marketplaceTitle: "Marketplace tokenisee", marketplaceEyebrow: "Tokens configures", marketplaceLead: "Projets avec un mint deja configure, prets pour les ordres, reservations ou emissions operationnelles.", offerStructure: "Structure de l'offre", reservedOf: "reserves sur", investAmount: "Montant a investir", paymentMethod: "Methode de paiement", testOrder: "Creer un ordre de test", keyData: "Donnees cles", target: "Objectif", minimum: "Minimum", expectedYield: "Rendement attendu", open: "Ouvrir", risk: "Risque", months: "mois", documents: "Documents", solanaEvents: "Evenements Solana simules", notFound: "Projet introuvable", categoryTitles: { "real-estate": "Projets immobiliers", agriculture: "Projets agricoles", art: "Projets artistiques", music: "Projets musicaux", tourism: "Projets touristiques", business: "Projets d'affaires", energy: "Projets energie" } });
Object.assign(shared.fr, { legalRulesTitle: "Regles operationnelles pour tokeniser en RD", legalSourcesTitle: "Sources reglementaires de reference", legalSourcesText: "Pour une utilisation en production, valider avec des avocats dominicains, la supervision des valeurs mobilieres, l'administration fiscale, l'unite d'analyse financiere et les positions de la Banque centrale sur les actifs virtuels.", legalRules: [["Pas de loi crypto specifique", "La Republique dominicaine ne dispose pas d'une loi complete specifique a la blockchain ou a la tokenisation. Chaque offre doit etre analysee selon les regles existantes sur les valeurs mobilieres, societes, impots, AML, donnees et propriete."], ["Pas de monnaie legale", "Les cryptoactifs ne sont pas une monnaie legale et ne sont pas garantis par la Banque centrale. La plateforme ne doit pas les presenter comme monnaie officielle ou garantie par l'Etat."], ["SIMV et Loi 249-17", "Si un token promet rendement, participation economique, dette, revenue share ou attente de profit par gestion de tiers, il peut etre traite comme valeur mobiliere."], ["AML/KYC requis", "Selon la Loi 155-17 et les criteres UAF, le flux doit identifier investisseurs et promoteurs, verifier origine des fonds, beneficiaire effectif, PEP, sanctions et suivi des transactions."], ["Impots et DGII", "Revenus, distributions, gains, ITBIS le cas echeant, retenues et rapports fiscaux doivent etre verifies localement."], ["Donnees personnelles", "Documents KYC, identites, passeports et etats financiers doivent etre stockes avec acces restreint, finalite claire, consentement et controles de securite."]] });

Object.keys(shared).forEach((lang) => Object.assign(dictionaries[lang], shared[lang]));

dictionaries.es.platformText = { eyebrow: "Plataforma de tokenizacion", audience: "Para promotores, desarrolladores, family offices e inversionistas internacionales.", values: ["Flujo de debida diligencia, documentacion del proyecto, elegibilidad del inversionista y visibilidad del cap table.", "Ofertas primarias, transferencias controladas, reportes operativos y seguimiento de distribuciones.", "Paginas profesionales por proyecto con visuales de calidad y lenguaje orientado a cumplimiento."] };
dictionaries.en.platformText = { eyebrow: "Tokenization platform", audience: "Built for issuers, developers, family offices, and cross-border investors.", values: ["Due diligence workflow, project documentation, investor eligibility, and cap table visibility.", "Primary offerings, controlled transfers, operational reporting, and distribution tracking.", "Professional project pages with quality visuals and compliance-first language."] };
dictionaries.de.platformText = { eyebrow: "Tokenisierungsplattform", audience: "Fuer Emittenten, Entwickler, Family Offices und internationale Investoren.", values: ["Due-Diligence-Workflow, Projektdokumentation, Investorenberechtigung und Cap-Table-Transparenz.", "Primaerangebote, kontrollierte Transfers, operative Berichte und Ausschuettungsverfolgung.", "Professionelle Projektseiten mit hochwertigen Visuals und Compliance-orientierter Sprache."] };
dictionaries.fr.platformText = { eyebrow: "Plateforme de tokenisation", audience: "Pour emetteurs, developpeurs, family offices et investisseurs internationaux.", values: ["Flux de due diligence, documentation du projet, eligibilite investisseur et visibilite du cap table.", "Offres primaires, transferts controles, reporting operationnel et suivi des distributions.", "Pages projet professionnelles avec visuels de qualite et langage oriente conformite."] };

dictionaries.es.dashboardText = { investor: "Inversionista", orderCreated: "Orden creada correctamente. Ya aparece abajo como pago pendiente.", investedReserved: "Invertido/reservado", orders: "Ordenes", walletTokens: "Wallet y tokens", issuedLocked: "Emitidos / bloqueados", reservedPending: "tokens reservados, pendientes de emision", amount: "Monto", pending: "pendiente", empty: "Sin tokens ni reservas todavia." };
dictionaries.en.dashboardText = { investor: "Investor", orderCreated: "Order created successfully. It now appears below as payment pending.", investedReserved: "Invested/reserved", orders: "Orders", walletTokens: "Wallet and tokens", issuedLocked: "Issued / locked", reservedPending: "reserved tokens pending issuance", amount: "Amount", pending: "pending", empty: "No tokens or reservations yet." };
dictionaries.de.dashboardText = { investor: "Investor", orderCreated: "Order erfolgreich erstellt. Sie erscheint unten als ausstehende Zahlung.", investedReserved: "Investiert/reserviert", orders: "Orders", walletTokens: "Wallet und Tokens", issuedLocked: "Ausgegeben / gesperrt", reservedPending: "reservierte Tokens, Ausgabe ausstehend", amount: "Betrag", pending: "ausstehend", empty: "Noch keine Tokens oder Reservierungen." };
dictionaries.fr.dashboardText = { investor: "Investisseur", orderCreated: "Ordre cree avec succes. Il apparait ci-dessous comme paiement en attente.", investedReserved: "Investi/reserve", orders: "Ordres", walletTokens: "Wallet et tokens", issuedLocked: "Emis / verrouilles", reservedPending: "tokens reserves, emission en attente", amount: "Montant", pending: "en attente", empty: "Aucun token ni reservation pour le moment." };

dictionaries.es.paymentMethods = { usdc: "USDC Solana", bank: "Transferencia bancaria" };
dictionaries.en.paymentMethods = { usdc: "USDC Solana", bank: "Bank transfer" };
dictionaries.de.paymentMethods = { usdc: "USDC Solana", bank: "Bankueberweisung" };
dictionaries.fr.paymentMethods = { usdc: "USDC Solana", bank: "Virement bancaire" };

dictionaries.es.invalidOrder = "Orden invalida";
dictionaries.en.invalidOrder = "Invalid order";
dictionaries.de.invalidOrder = "Ungueltige Order";
dictionaries.fr.invalidOrder = "Ordre invalide";
dictionaries.es.auditCreatedOrder = "tokens reservados por";
dictionaries.en.auditCreatedOrder = "tokens reserved for";
dictionaries.de.auditCreatedOrder = "Tokens reserviert fuer";
dictionaries.fr.auditCreatedOrder = "tokens reserves pour";

dictionaries.es.legalCardTitles = ["Token != titulo", "Valores mobiliarios", "Registro separado"];
dictionaries.en.legalCardTitles = ["Token != title", "Securities", "Separate records"];
dictionaries.de.legalCardTitles = ["Token != Titel", "Wertpapiere", "Getrennte Register"];
dictionaries.fr.legalCardTitles = ["Token != titre", "Valeurs mobilieres", "Registres separes"];

function getLang(req) {
  const queryLang = req.query.lang;
  if (queryLang && dictionaries[queryLang]) return queryLang;
  const cookieLang = (req.cookies || {}).tokenizas_lang;
  return dictionaries[cookieLang] ? cookieLang : "es";
}

function tr(req) {
  return dictionaries[getLang(req)];
}

module.exports = { getLang, tr };
