const dictionaries = {
  es: {
    projects: "Proyectos", invest: "Invertir", dashboard: "Dashboard", legal: "Ley RD", contact: "Contacto", whatsapp: "WhatsApp",
    heroEyebrow: "Tokenizacion inmobiliaria en Solana", heroTitle: "Invierte de forma fraccionada en proyectos inmobiliarios dominicanos.", heroLead: "Plataforma demo para originar activos, validar inversionistas, estructurar ofertas, emitir tokens controlados y administrar distribuciones.",
    viewProjects: "Ver proyectos", createOrder: "Crear orden", pilotProjects: "Proyectos piloto", targetCapital: "Capital objetivo", reservedCapital: "Capital reservado", pipeline: "Pipeline", readyAssets: "Activos listos para pruebas",
    modulesTitle: "Una plataforma completa para tokenizar activos", modulesLead: "Integramos originacion, cumplimiento, contratos, inversionistas y operaciones en una sola experiencia.", backOffice: "Back office de activos", backOfficeText: "Gestion de cartera, documentos, estados de ofertas, solicitudes de inversionistas y registro de auditoria.", smartContracts: "Motor blockchain", smartContractsText: "Emision controlada de tokens en Solana, reglas de transferencia, whitelist y eventos verificables.", investorPortal: "Portal del inversionista", investorPortalText: "Dashboard con proyectos, tokens, ordenes, distribuciones y documentos relevantes.", landingPages: "Paginas por proyecto", landingPagesText: "Fichas comerciales optimizadas con imagenes, estructura legal, metricas, riesgos y llamados a inversion.", advantagesTitle: "Por que elegir Tokenizas Dominicana", demoTitle: "Agenda una consulta",
    legalTitle: "Marco legal sobre tokens en Republica Dominicana", legalLead: "Republica Dominicana no tiene una ley cripto integral especifica para tokenizacion inmobiliaria. El camino prudente es estructurar ofertas que puedan calificar como valores bajo la Ley 249-17 y la supervision de la SIMV, con KYC/AML, documentacion de oferta y proteccion al inversionista. Los criptoactivos no son moneda de curso legal ni tienen respaldo del Banco Central.", legal1: "Un token inmobiliario no debe presentarse como titulo de propiedad registrado. Normalmente representa un derecho economico, contractual o participacion en un vehiculo legal.", legal2: "Si el token funciona como valor mobiliario, debe revisarse con asesores legales y, cuando aplique, con la Superintendencia del Mercado de Valores.", legal3: "La plataforma debe separar claramente registro legal, contratos, cap table interno y registro blockchain.",
    contactTitle: "Solicita mas informacion", contactLead: "Cuentanos sobre tu proyecto, inmueble o perfil de inversionista. Te contactaremos por email o WhatsApp.", name: "Nombre", company: "Empresa", email: "Email", phone: "WhatsApp", interest: "Interes", message: "Mensaje", consent: "Acepto ser contactado sobre Tokenizas Dominicana.", send: "Enviar solicitud", leadSaved: "Solicitud recibida. Te contactaremos pronto.",
    loginTitle: "Panel administrativo", loginLead: "Ingresa tus credenciales para administrar proyectos, KYC y auditoria.", privateAccess: "Acceso privado", username: "Usuario", password: "Clave", enter: "Entrar", logout: "Cerrar sesion"
  },
  en: {
    projects: "Projects", invest: "Invest", dashboard: "Dashboard", legal: "DR Law", contact: "Contact", whatsapp: "WhatsApp",
    heroEyebrow: "Real estate tokenization on Solana", heroTitle: "Fractional access to Dominican real estate projects.", heroLead: "A demo platform to originate assets, validate investors, structure offerings, issue controlled tokens, and manage distributions.",
    viewProjects: "View projects", createOrder: "Create order", pilotProjects: "Pilot projects", targetCapital: "Target capital", reservedCapital: "Reserved capital", pipeline: "Pipeline", readyAssets: "Assets ready for testing",
    modulesTitle: "A complete platform for asset tokenization", modulesLead: "Origination, compliance, contracts, investors, and operations in one experience.", backOffice: "Asset back office", backOfficeText: "Portfolio management, documents, offering status, investor requests, and audit records.", smartContracts: "Blockchain engine", smartContractsText: "Controlled Solana token issuance, transfer rules, whitelist, and verifiable events.", investorPortal: "Investor portal", investorPortalText: "Dashboard with projects, tokens, orders, distributions, and documents.", landingPages: "Project pages", landingPagesText: "Commercial pages with images, legal structure, metrics, risks, and investment calls to action.", advantagesTitle: "Why choose Tokenizas Dominicana", demoTitle: "Book a consultation",
    legalTitle: "Token law in the Dominican Republic", legalLead: "The Dominican Republic does not yet have a comprehensive crypto statute specifically for real estate tokenization. The prudent route is to structure offerings that may qualify as securities under Law 249-17 and SIMV supervision, with KYC/AML, offering documents, and investor protection. Cryptoassets are not legal tender and are not backed by the Central Bank.", legal1: "A real estate token should not be presented as a registered property title. It usually represents an economic, contractual, or vehicle-level right.", legal2: "If the token behaves as a security, it should be reviewed by counsel and, where applicable, the securities regulator.", legal3: "The platform must clearly separate the legal registry, contracts, internal cap table, and blockchain record.",
    contactTitle: "Request more information", contactLead: "Tell us about your project, property, or investor profile. We will contact you by email or WhatsApp.", name: "Name", company: "Company", email: "Email", phone: "WhatsApp", interest: "Interest", message: "Message", consent: "I agree to be contacted about Tokenizas Dominicana.", send: "Send request", leadSaved: "Request received. We will contact you soon.",
    loginTitle: "Admin panel", loginLead: "Enter your credentials to manage projects, KYC, and audit records.", privateAccess: "Private access", username: "Username", password: "Password", enter: "Sign in", logout: "Log out"
  },
  de: {
    projects: "Projekte", invest: "Investieren", dashboard: "Dashboard", legal: "Recht RD", contact: "Kontakt", whatsapp: "WhatsApp",
    heroEyebrow: "Immobilien-Tokenisierung auf Solana", heroTitle: "Fraktionierter Zugang zu Immobilienprojekten in der Dominikanischen Republik.", heroLead: "Demo-Plattform fuer Asset-Originierung, Investorenpruefung, Angebotsstrukturierung, kontrollierte Token-Ausgabe und Ausschuettungen.",
    viewProjects: "Projekte ansehen", createOrder: "Order erstellen", pilotProjects: "Pilotprojekte", targetCapital: "Zielkapital", reservedCapital: "Reserviertes Kapital", pipeline: "Pipeline", readyAssets: "Assets fuer Tests bereit",
    modulesTitle: "Eine komplette Plattform fuer Asset-Tokenisierung", modulesLead: "Originierung, Compliance, Vertraege, Investoren und Betrieb in einer Erfahrung.", backOffice: "Asset Back Office", backOfficeText: "Portfolioverwaltung, Dokumente, Angebotsstatus, Investorenanfragen und Auditprotokolle.", smartContracts: "Blockchain Engine", smartContractsText: "Kontrollierte Solana-Token-Ausgabe, Transferregeln, Whitelist und pruefbare Events.", investorPortal: "Investorenportal", investorPortalText: "Dashboard mit Projekten, Tokens, Orders, Ausschuettungen und Dokumenten.", landingPages: "Projektseiten", landingPagesText: "Kommerzielle Seiten mit Bildern, Rechtsstruktur, Kennzahlen, Risiken und Investment-Aufrufen.", advantagesTitle: "Warum Tokenizas Dominicana", demoTitle: "Beratung buchen",
    legalTitle: "Token-Rechtslage in der Dominikanischen Republik", legalLead: "Die Dominikanische Republik hat noch kein umfassendes Kryptogesetz speziell fuer Immobilien-Tokenisierung. Der vorsichtige Weg ist eine Strukturierung als moegliches Wertpapier unter Gesetz 249-17 und SIMV-Aufsicht, mit KYC/AML, Offenlegungsunterlagen und Investorenschutz.", legal1: "Ein Immobilien-Token sollte nicht als registrierter Eigentumstitel dargestellt werden. Meist repraesentiert er ein wirtschaftliches, vertragliches oder vehikelbezogenes Recht.", legal2: "Wenn der Token wie ein Wertpapier wirkt, sollte er rechtlich und gegebenenfalls mit der Wertpapieraufsicht geprueft werden.", legal3: "Die Plattform muss Grundbuch, Vertraege, interne Beteiligungstabelle und Blockchain-Eintrag klar trennen.",
    contactTitle: "Weitere Informationen anfordern", contactLead: "Erzaehle uns von deinem Projekt, deiner Immobilie oder deinem Anlegerprofil. Wir melden uns per E-Mail oder WhatsApp.", name: "Name", company: "Unternehmen", email: "E-Mail", phone: "WhatsApp", interest: "Interesse", message: "Nachricht", consent: "Ich stimme zu, zu Tokenizas Dominicana kontaktiert zu werden.", send: "Anfrage senden", leadSaved: "Anfrage erhalten. Wir melden uns bald.",
    loginTitle: "Adminbereich", loginLead: "Melde dich an, um Projekte, KYC und Auditdaten zu verwalten.", privateAccess: "Privater Zugang", username: "Benutzer", password: "Passwort", enter: "Einloggen", logout: "Abmelden"
  },
  fr: {
    projects: "Projets", invest: "Investir", dashboard: "Tableau", legal: "Loi RD", contact: "Contact", whatsapp: "WhatsApp",
    heroEyebrow: "Tokenisation immobiliere sur Solana", heroTitle: "Acces fractionne aux projets immobiliers dominicains.", heroLead: "Plateforme de demo pour sourcer les actifs, verifier les investisseurs, structurer les offres, emettre des tokens controles et gerer les distributions.",
    viewProjects: "Voir les projets", createOrder: "Creer un ordre", pilotProjects: "Projets pilotes", targetCapital: "Capital cible", reservedCapital: "Capital reserve", pipeline: "Pipeline", readyAssets: "Actifs prets pour les tests",
    modulesTitle: "Une plateforme complete pour la tokenisation d'actifs", modulesLead: "Origination, conformite, contrats, investisseurs et operations dans une seule experience.", backOffice: "Back office actifs", backOfficeText: "Gestion de portefeuille, documents, statut des offres, demandes investisseurs et audit.", smartContracts: "Moteur blockchain", smartContractsText: "Emission controlee de tokens Solana, regles de transfert, whitelist et evenements verifiables.", investorPortal: "Portail investisseur", investorPortalText: "Tableau avec projets, tokens, ordres, distributions et documents.", landingPages: "Pages projet", landingPagesText: "Pages commerciales avec images, structure legale, indicateurs, risques et appels a investir.", advantagesTitle: "Pourquoi choisir Tokenizas Dominicana", demoTitle: "Planifier une consultation",
    legalTitle: "Cadre juridique des tokens en Republique dominicaine", legalLead: "La Republique dominicaine ne dispose pas encore d'une loi crypto complete specifique a la tokenisation immobiliere. La voie prudente consiste a structurer les offres pouvant etre qualifiees de valeurs mobilieres sous la Loi 249-17 et la supervision de la SIMV, avec KYC/AML, documents d'information et protection des investisseurs.", legal1: "Un token immobilier ne doit pas etre presente comme un titre de propriete enregistre. Il represente generalement un droit economique, contractuel ou lie a un vehicule juridique.", legal2: "Si le token fonctionne comme une valeur mobiliere, il doit etre examine par des conseillers juridiques et, le cas echeant, par le regulateur des valeurs mobilieres.", legal3: "La plateforme doit separer clairement le registre legal, les contrats, le cap table interne et l'enregistrement blockchain.",
    contactTitle: "Demander plus d'informations", contactLead: "Parlez-nous de votre projet, bien immobilier ou profil investisseur. Nous vous contacterons par email ou WhatsApp.", name: "Nom", company: "Entreprise", email: "Email", phone: "WhatsApp", interest: "Interet", message: "Message", consent: "J'accepte d'etre contacte au sujet de Tokenizas Dominicana.", send: "Envoyer", leadSaved: "Demande recue. Nous vous contacterons bientot.",
    loginTitle: "Panneau admin", loginLead: "Connectez-vous pour gerer les projets, KYC et journaux d'audit.", privateAccess: "Acces prive", username: "Utilisateur", password: "Mot de passe", enter: "Connexion", logout: "Deconnexion"
  }
};

function getLang(req) {
  const queryLang = req.query.lang;
  if (queryLang && dictionaries[queryLang]) return queryLang;
  const cookieLang = (req.cookies || {}).tokenizas_lang;
  return dictionaries[cookieLang] ? cookieLang : "es";
}

function tr(req) {
  return dictionaries[getLang(req)];
}

module.exports = { getLang, tr };
